### ISSUE TITLE
[Brokernode] Deployment Problems

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#572]
While trying to deploy I have encountered some new problems.  Filing here so we don't lose track.  These errors seem to be unique to the prod environment because I did not encounter them on my test brokers.  

-Broker does not see transactions on tangle with lambda enabled
-poll.oysternodes.com seems to be taking forever
-Beta broker does not seem to be doing any work
-MustDecodeBig error:
panic: hex string "0x"

goroutine 75194 [running]:
github.com/ethereum/go-ethereum/common/hexutil.MustDecodeBig(0xf2cb04, 0x2, 0x2)
        /go/src/github.com/ethereum/go-ethereum/common/hexutil/hexutil.go:173 +0x6f
github.com/oysterprotocol/brokernode/services.generateEthAddrFromPrivateKey(0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/oysterprotocol/brokernode/services/eth_gateway.go:386 +0x10d
github.com/oysterprotocol/brokernode/jobs.StageTreasures(0xc429b9c960, 0x1, 0x1, 0x274465c6297cf3b9, 0xf678a33308e63487, 0x0, 0xed3262566, 0x0, 0x0, 0xed326258e, ...)
        /go/src/github.com/oysterprotocol/brokernode/jobs/process_unassigned_chunks.go:264 +0x489
github.com/oysterprotocol/brokernode/jobs.FilterAndAssignChunksToChannels(0xc436978000, 0x393, 0x45d, 0xc42c014000, 0xf, 0x10, 0xfe88e8, 0xfe88f0, 0xfe8918, 0xfe8920, ...)
        /go/src/github.com/oysterprotocol/brokernode/jobs/process_unassigned_chunks.go:128 +0x801
github.com/oysterprotocol/brokernode/jobs.GetSessionUnassignedChunks(0xc42c000240, 0x1, 0x1, 0xfe88e8, 0xfe88f0, 0xfe8918, 0xfe8920, 0xfe8828, 0xfe8928, 0xfe8848, ...)
        /go/src/github.com/oysterprotocol/brokernode/jobs/process_unassigned_chunks.go:43 +0x205
github.com/oysterprotocol/brokernode/jobs.ProcessUnassignedChunks(0xfe88e8, 0xfe88f0, 0xfe8918, 0xfe8920, 0xfe8828, 0xfe8928, 0xfe8848, 0xfe88a0, 0xfe88d8, 0xfe88b8, ...)
        /go/src/github.com/oysterprotocol/brokernode/jobs/process_unassigned_chunks.go:27 +0xb6
github.com/oysterprotocol/brokernode/jobs.processUnassignedChunksHandler(0xc4203a0ae0, 0x3, 0xc4200380d0)
        /go/src/github.com/oysterprotocol/brokernode/jobs/job_runner.go:118 +0xac
github.com/gobuffalo/buffalo/worker.Simple.Perform.func1(0xfe87a8, 0xf3188a, 0x7, 0xc4203a0ae0, 0x1549a48, 0x48, 0x10b4f00, 0xc420460230, 0x10b2160, 0xc42049c200, ...)
        /go/src/github.com/gobuffalo/buffalo/worker/simple.go:85 +0x3a
created by github.com/gobuffalo/buffalo/worker.Simple.Perform
        /go/src/github.com/gobuffalo/buffalo/worker/simple.go:84 +0x528
buffalo: 2018/09/08 20:19:59 === exit status 2  

I suspect the last error is likely encryption/decryption related.  The private key returned from `generateEthAddr` when the broker first creates the session should be fine.  There is some checking in `generateEthAddr` that should prevent any invalid keys being created.

**Comment by MrRedPandabear** [comment]
@rfornea @braddoge

**Comment by MrRedPandabear** [comment]
@MrRedPandabear That was not my intention

**Comment by pzhao5** [comment]
@rfornea is that still happening for recent prod deployment?

**Comment by pzhao5** [comment]
You mean "Broker does not see transactions on tangle with lambda enabled"?
Where do we check this transaction? as a background job?

**Comment by rfornea** [comment]
Yes "Broker does not see transactions on tangle with lambda enabled".  There is a `VerifyDataMaps` task that runs in the background once all the attachment is completed for a file, and it tries to verify that all the chunks have been attached.  But the queries to the tangle do not show the chunks as having been attached.  The front end's polling of the tangle also does not show the chunks as having been attached.  

I'd have to double-check but I think this issue does not occur on dev brokers, but only on the prod brokers.

**Comment by pzhao5** [comment]
And do you suspect this on Lamdba?

**Comment by rfornea** [comment]
I'm not sure.  It could be something to do with lambda, or it could just be that we're overwhelming the tangle too quickly and it's dropping transactions.

**Comment by pzhao5** [comment]
If that is the case, then we should expect to see any sentry error. But currently, there is not error at all. @AaronVasquez, do you configure it correct? I have not seen any data from lambda-node in sentry.

**Comment by AaronVasquez** [comment]
I just checked, and Sentry was misconfigured :/ I fixed it now, but those errors were never recorded.

**Comment by rfornea** [comment]
Cool. Well, tomorrow we can deploy the change and put the prod brokers in lambda mode and see what errors we get. Hopefully it's something simple to fix.

**Comment by rfornea** [comment]
All these are fixed now.

**Comment by pzhao5** [comment]
@rfornea, fixed as Lamdba is working as expected? I have looked into AWS console, it returns 200 for all prod code (as well as dev) which mean that there is not error during the run which mean the transaction is attached to tangle.

**Comment by rfornea** [comment]
Yeah it's all working as expected. It turned out that the problem in prod was that we were making requests to lambda that were too large.

**Comment by pzhao5** [comment]
How large is too large?

**Comment by pzhao5** [comment]
And how do you find out about it?

**Comment by rfornea** [comment]
Initially, prod was sending requests with up to 1000 chunks in it.  That was too big.  I saw an error in Sentry about it.  I kept reducing the maxiumum number of chunks until the transactions started showing up on the tangle.  Now it will send a max of 300 chunks at a time.

**Comment by pzhao5** [comment]
Hmm! I would expect some error message in the brokernode! Since brokernode sends the request to lamdba and it would return 500. I was not able to find any error on brokernode side. When I looked at the cloud watch log for lamdba, it did not show any 500. Maybe I just missed something.
